-- DDL generated by Postico 1.5.21
-- Not all database features are supported. Do not use for backup.
-- Table Definition ----------------------------------------------

CREATE TABLE imperial_tasks (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text NOT NULL,
    status text NOT NULL DEFAULT 'Not Completed'::text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX imperial_tasks_pkey ON imperial_tasks(id int4_ops);
